export interface HardwareCategorySeed {
  name: string;
  slug: string;
  description: string;
}

export interface ProductBlueprint {
  name: string;
  categorySlug: string;
  skuPrefix: string;
  costRange: [number, number];
  marginRange: [number, number];
  lowStockThresholdRange: [number, number];
  demandWeight: number;
}

export const HARDWARE_CATEGORIES: HardwareCategorySeed[] = [
  {
    name: 'Power Tools',
    slug: 'power-tools',
    description:
      'Cordless and electric tools for drilling, cutting, grinding, and sanding.',
  },
  {
    name: 'Hand Tools',
    slug: 'hand-tools',
    description:
      'Essential manual tools for workshops, contractors, and home maintenance.',
  },
  {
    name: 'Electrical',
    slug: 'electrical',
    description:
      'Wiring accessories, switches, breakers, and power distribution products.',
  },
  {
    name: 'Plumbing',
    slug: 'plumbing',
    description:
      'Pipes, fittings, valves, and fixtures for water and drainage systems.',
  },
  {
    name: 'Fasteners',
    slug: 'fasteners',
    description:
      'Screws, anchors, nuts, washers, and nails for construction and repairs.',
  },
  {
    name: 'Paint & Finishing',
    slug: 'paint-finishing',
    description:
      'Coatings and finishing supplies for indoor and outdoor improvement jobs.',
  },
  {
    name: 'Safety Gear',
    slug: 'safety-gear',
    description:
      'Personal protective equipment for safe work on construction sites.',
  },
  {
    name: 'Building Materials',
    slug: 'building-materials',
    description:
      'Core materials and consumables used across civil and finishing projects.',
  },
];

export const HARDWARE_PRODUCT_BLUEPRINTS: ProductBlueprint[] = [
  {
    name: 'Cordless Drill 12V',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [34, 49],
    marginRange: [0.19, 0.31],
    lowStockThresholdRange: [6, 12],
    demandWeight: 1.35,
  },
  {
    name: 'Hammer Drill 18V',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [55, 79],
    marginRange: [0.16, 0.28],
    lowStockThresholdRange: [4, 10],
    demandWeight: 1.05,
  },
  {
    name: 'Angle Grinder 4.5in',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [42, 66],
    marginRange: [0.17, 0.29],
    lowStockThresholdRange: [5, 11],
    demandWeight: 1.1,
  },
  {
    name: 'Circular Saw 7-1/4in',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [62, 91],
    marginRange: [0.16, 0.27],
    lowStockThresholdRange: [4, 9],
    demandWeight: 0.85,
  },
  {
    name: 'Jigsaw Variable Speed',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [38, 57],
    marginRange: [0.18, 0.3],
    lowStockThresholdRange: [4, 10],
    demandWeight: 0.78,
  },
  {
    name: 'Orbital Sander 240W',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [29, 45],
    marginRange: [0.2, 0.32],
    lowStockThresholdRange: [5, 11],
    demandWeight: 0.72,
  },
  {
    name: 'Heat Gun 2000W',
    categorySlug: 'power-tools',
    skuPrefix: 'PT',
    costRange: [24, 39],
    marginRange: [0.2, 0.33],
    lowStockThresholdRange: [4, 9],
    demandWeight: 0.58,
  },
  {
    name: 'Claw Hammer 16oz',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [6, 11],
    marginRange: [0.22, 0.36],
    lowStockThresholdRange: [10, 20],
    demandWeight: 1.5,
  },
  {
    name: 'Screwdriver Set 12pc',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [8, 15],
    marginRange: [0.21, 0.34],
    lowStockThresholdRange: [8, 18],
    demandWeight: 1.42,
  },
  {
    name: 'Adjustable Wrench 10in',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [7, 14],
    marginRange: [0.2, 0.33],
    lowStockThresholdRange: [8, 16],
    demandWeight: 1.18,
  },
  {
    name: 'Pliers Set 3pc',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [9, 16],
    marginRange: [0.19, 0.32],
    lowStockThresholdRange: [7, 14],
    demandWeight: 1.12,
  },
  {
    name: 'Tape Measure 8m',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [4, 8],
    marginRange: [0.24, 0.37],
    lowStockThresholdRange: [12, 24],
    demandWeight: 1.62,
  },
  {
    name: 'Utility Knife Heavy Duty',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [3, 7],
    marginRange: [0.24, 0.38],
    lowStockThresholdRange: [12, 24],
    demandWeight: 1.36,
  },
  {
    name: 'Wood Chisel Set 4pc',
    categorySlug: 'hand-tools',
    skuPrefix: 'HT',
    costRange: [10, 18],
    marginRange: [0.2, 0.31],
    lowStockThresholdRange: [6, 12],
    demandWeight: 0.62,
  },
  {
    name: 'LED Bulb E27 12W',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [1.4, 2.8],
    marginRange: [0.25, 0.39],
    lowStockThresholdRange: [30, 70],
    demandWeight: 1.95,
  },
  {
    name: 'Extension Cord 10m',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [7, 13],
    marginRange: [0.19, 0.31],
    lowStockThresholdRange: [10, 20],
    demandWeight: 1.22,
  },
  {
    name: 'Power Strip 6 Outlet',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [5, 10],
    marginRange: [0.22, 0.35],
    lowStockThresholdRange: [10, 20],
    demandWeight: 1.16,
  },
  {
    name: 'Mini Circuit Breaker 32A',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [3.8, 7.2],
    marginRange: [0.23, 0.36],
    lowStockThresholdRange: [15, 30],
    demandWeight: 1.05,
  },
  {
    name: 'Electrical Tape Black',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [0.45, 0.95],
    marginRange: [0.28, 0.4],
    lowStockThresholdRange: [35, 80],
    demandWeight: 1.54,
  },
  {
    name: 'Copper Wire Roll 2.5mm',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [18, 29],
    marginRange: [0.17, 0.28],
    lowStockThresholdRange: [6, 12],
    demandWeight: 0.88,
  },
  {
    name: 'Wall Switch 1 Gang',
    categorySlug: 'electrical',
    skuPrefix: 'EL',
    costRange: [0.9, 1.9],
    marginRange: [0.27, 0.39],
    lowStockThresholdRange: [25, 55],
    demandWeight: 1.3,
  },
  {
    name: 'PVC Pipe 1in x 3m',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [4.5, 8.4],
    marginRange: [0.2, 0.33],
    lowStockThresholdRange: [14, 28],
    demandWeight: 1.18,
  },
  {
    name: 'Ball Valve 1in',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [3.2, 6.8],
    marginRange: [0.22, 0.35],
    lowStockThresholdRange: [12, 24],
    demandWeight: 1.1,
  },
  {
    name: 'Pipe Wrench 14in',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [11, 19],
    marginRange: [0.18, 0.29],
    lowStockThresholdRange: [6, 14],
    demandWeight: 0.82,
  },
  {
    name: 'Thread Seal Tape PTFE',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [0.35, 0.85],
    marginRange: [0.28, 0.4],
    lowStockThresholdRange: [35, 75],
    demandWeight: 1.48,
  },
  {
    name: 'Kitchen Faucet Chrome',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [24, 39],
    marginRange: [0.16, 0.27],
    lowStockThresholdRange: [4, 8],
    demandWeight: 0.65,
  },
  {
    name: 'Shower Hose 1.5m',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [4.8, 9.2],
    marginRange: [0.21, 0.33],
    lowStockThresholdRange: [10, 22],
    demandWeight: 0.9,
  },
  {
    name: 'PVC Elbow 1in Pack',
    categorySlug: 'plumbing',
    skuPrefix: 'PL',
    costRange: [1.1, 2.4],
    marginRange: [0.26, 0.39],
    lowStockThresholdRange: [30, 60],
    demandWeight: 1.36,
  },
  {
    name: 'Wood Screws Box 50',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [2.1, 4.1],
    marginRange: [0.24, 0.38],
    lowStockThresholdRange: [22, 50],
    demandWeight: 1.68,
  },
  {
    name: 'Anchor Bolts Pack 10',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [2.6, 4.8],
    marginRange: [0.22, 0.35],
    lowStockThresholdRange: [18, 40],
    demandWeight: 1.36,
  },
  {
    name: 'Hex Nut M10 Pack 25',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [1.2, 2.6],
    marginRange: [0.24, 0.37],
    lowStockThresholdRange: [26, 55],
    demandWeight: 1.28,
  },
  {
    name: 'Washer M10 Pack 25',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [0.95, 2.1],
    marginRange: [0.25, 0.38],
    lowStockThresholdRange: [26, 55],
    demandWeight: 1.22,
  },
  {
    name: 'Drywall Screws Box 100',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [3.1, 5.8],
    marginRange: [0.22, 0.34],
    lowStockThresholdRange: [18, 42],
    demandWeight: 1.42,
  },
  {
    name: 'Masonry Nails Box 1kg',
    categorySlug: 'fasteners',
    skuPrefix: 'FS',
    costRange: [4, 7.1],
    marginRange: [0.21, 0.33],
    lowStockThresholdRange: [14, 32],
    demandWeight: 1.08,
  },
  {
    name: 'Acrylic Wall Paint 4L',
    categorySlug: 'paint-finishing',
    skuPrefix: 'PF',
    costRange: [9, 15],
    marginRange: [0.19, 0.31],
    lowStockThresholdRange: [8, 18],
    demandWeight: 1.12,
  },
  {
    name: 'Paint Roller Kit 9in',
    categorySlug: 'paint-finishing',
    skuPrefix: 'PF',
    costRange: [3.2, 6.2],
    marginRange: [0.23, 0.36],
    lowStockThresholdRange: [12, 24],
    demandWeight: 1.05,
  },
  {
    name: 'Paint Brush 2in',
    categorySlug: 'paint-finishing',
    skuPrefix: 'PF',
    costRange: [1.8, 3.8],
    marginRange: [0.24, 0.38],
    lowStockThresholdRange: [18, 40],
    demandWeight: 1.2,
  },
  {
    name: 'Sandpaper Assorted Pack',
    categorySlug: 'paint-finishing',
    skuPrefix: 'PF',
    costRange: [1.4, 2.9],
    marginRange: [0.25, 0.39],
    lowStockThresholdRange: [20, 44],
    demandWeight: 1.15,
  },
  {
    name: 'Wood Varnish 1L',
    categorySlug: 'paint-finishing',
    skuPrefix: 'PF',
    costRange: [6.5, 11.8],
    marginRange: [0.2, 0.33],
    lowStockThresholdRange: [8, 16],
    demandWeight: 0.76,
  },
  {
    name: 'Work Gloves Pair',
    categorySlug: 'safety-gear',
    skuPrefix: 'SG',
    costRange: [1.7, 3.4],
    marginRange: [0.24, 0.38],
    lowStockThresholdRange: [20, 45],
    demandWeight: 1.38,
  },
  {
    name: 'Safety Goggles Clear',
    categorySlug: 'safety-gear',
    skuPrefix: 'SG',
    costRange: [2.2, 4.4],
    marginRange: [0.23, 0.36],
    lowStockThresholdRange: [15, 34],
    demandWeight: 1.1,
  },
  {
    name: 'Dust Mask N95 Pack 10',
    categorySlug: 'safety-gear',
    skuPrefix: 'SG',
    costRange: [3.8, 7],
    marginRange: [0.21, 0.34],
    lowStockThresholdRange: [14, 32],
    demandWeight: 1.16,
  },
  {
    name: 'Ear Protection Muffs',
    categorySlug: 'safety-gear',
    skuPrefix: 'SG',
    costRange: [4.5, 8.3],
    marginRange: [0.2, 0.33],
    lowStockThresholdRange: [10, 22],
    demandWeight: 0.7,
  },
  {
    name: 'Safety Helmet ABS',
    categorySlug: 'safety-gear',
    skuPrefix: 'SG',
    costRange: [5.5, 9.8],
    marginRange: [0.2, 0.32],
    lowStockThresholdRange: [10, 22],
    demandWeight: 0.84,
  },
  {
    name: 'Cement Bag 25kg',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [4.4, 6.3],
    marginRange: [0.16, 0.24],
    lowStockThresholdRange: [35, 80],
    demandWeight: 1.5,
  },
  {
    name: 'Gypsum Board 12mm',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [6.8, 10.5],
    marginRange: [0.16, 0.25],
    lowStockThresholdRange: [18, 42],
    demandWeight: 1.14,
  },
  {
    name: 'Silicone Sealant Tube',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [1.7, 3.2],
    marginRange: [0.24, 0.37],
    lowStockThresholdRange: [20, 44],
    demandWeight: 1.24,
  },
  {
    name: 'Construction Adhesive',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [2.4, 4.8],
    marginRange: [0.23, 0.36],
    lowStockThresholdRange: [16, 36],
    demandWeight: 1.08,
  },
  {
    name: 'Tile Spacer Pack 200',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [1.1, 2.4],
    marginRange: [0.25, 0.38],
    lowStockThresholdRange: [24, 52],
    demandWeight: 0.94,
  },
  {
    name: 'Masonry Trowel Carbon Steel',
    categorySlug: 'building-materials',
    skuPrefix: 'BM',
    costRange: [5.2, 9.1],
    marginRange: [0.2, 0.31],
    lowStockThresholdRange: [8, 18],
    demandWeight: 0.74,
  },
];
